{{- if and (or (eq "lighthouse" .Values.jxRequirements.webhook) (eq "prow" .Values.jxRequirements.webhook)) (eq "istio" .Values.jxRequirements.ingress.kind) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hook
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - hook{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    port:
      name: http
      number: 80
      protocol: HTTP
{{- if .Values.jxRequirements.ingress.tls.enabled }}      
  - hosts:
    - hook{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    port:
      name: hook:0
      number: 443
      protocol: HTTPS
    tls:
{{- if .Values.hook.ingress.tls.secretName }}
      credentialName: "{{ .Values.hook.ingress.tls.secretName }}"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
      credentialName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else if .Values.jxRequirements.ingress.tls.production }}
      credentialName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else }}
      credentialName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- end }}
{{- end }}         
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hook
spec:
  gateways:
  - jx/hook
  hosts:
    - hook{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: hook
      weight: 100
{{- end }}