{{- if and (eq "bucketrepo" .Values.jxRequirements.repository) (eq "istio" .Values.jxRequirements.ingress.kind) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bucketrepo
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    port:
      name: http
      number: 80
      protocol: HTTP
{{- if .Values.jxRequirements.ingress.tls.enabled }}       
  - hosts:
    - bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    port:
      name: bucket:0
      number: 443
      protocol: HTTPS
    tls:
{{- if .Values.bucketrepo.ingress.tls.secretName }}
      credentialName: "{{ .Values.bucketrepo.ingress.tls.secretName }}"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
      credentialName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else if .Values.jxRequirements.ingress.tls.production }}
      credentialName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- else }}
      credentialName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
      mode: SIMPLE
      privateKey: tls.key
      serverCertificate: tls.crt
{{- end }}
{{- end }}            
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bucketrepo
spec:
  gateways:
  - jx/bucketrepo
  hosts:
    - bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: bucketrepo
      weight: 100
{{- end }}