{{- if (index .Values "docker-registry" "enabled")  }}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1beta1" }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-secret: jx-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
    jenkins.io/host: "{{ .Values.jxRequirements.ingress.domain }}"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: docker-registry
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jenkins-x-docker-registry
          servicePort: 5000
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/docker-registry"
{{- else if .Values.ingress.customHosts.dockerRegistry }}
        path: "/"
    host: {{ .Values.ingress.customHosts.dockerRegistry }}
{{- else if .Values.jxRequirements.ingress.domain }}
        path: "/"
    host: {{ .Values.ingress.prefix.dockerRegistry }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.customHosts.dockerRegistry }}
    - {{ .Values.ingress.customHosts.dockerRegistry }}
  {{- else }}
    - {{ .Values.ingress.prefix.dockerRegistry }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  {{- end }}
{{- if index .Values "docker-registry" "ingress" "tls" "secretName" }}
    secretName: "{{ index .Values "docker-registry" "ingress" "tls" "secretName" }}"
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
