apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-cfg
type: Opaque
data:
{{- if .Values.secrets.dockerConfig }}
  config.json: {{ .Values.secrets.dockerConfig | b64enc | quote }}
{{- else }}
  config.json: ""
{{- end }}
