{{- if eq .Values.jxRequirements.autoUpdate.enabled true }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-boot-upgrade
  labels:
    app: jenkins-x-upgrade-processor
    release: jx
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jenkins-x-upgrade-processor
            release: jx
        spec:
          containers:
          - args:
            - boot
            - upgrade
            - --git-credentials
            - --batch-mode
            command:
            - jxl
            env:
            - name: HOME
              value: /home
            image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl:{{ .Values.versions.jxl }}
            imagePullPolicy: Always
            name: jenkins-x-upgrade-processor
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  successfulJobsHistoryLimit: 3
  schedule: {{ .Values.jxRequirements.autoUpdate.schedule | default "0 12 */5 * *" | quote }}
  suspend: false
{{- end }}
